version: '3'
services:
  web:
    build: .
    restart: always
    ports:
      - 80:8080
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
volumes:
 mongodb: